PROJ = usb_serial
USB_CORE = ../common/usb/
ADD_SRC = \
		$(USB_CORE)edge_detect.v \
		$(USB_CORE)serial.v \
		$(USB_CORE)usb_fs_in_arb.v \
		$(USB_CORE)usb_fs_in_pe.v \
		$(USB_CORE)usb_fs_out_arb.v \
		$(USB_CORE)usb_fs_out_pe.v \
		$(USB_CORE)usb_fs_pe.v \
		$(USB_CORE)usb_fs_rx.v \
		$(USB_CORE)usb_fs_tx_mux.v \
		$(USB_CORE)usb_fs_tx.v \
		$(USB_CORE)usb_reset_det.v \
		$(USB_CORE)usb_serial_ctrl_ep.v \
		$(USB_CORE)usb_uart_bridge_ep.v \
		$(USB_CORE)usb_uart_core.v \
		$(USB_CORE)usb_uart_ecp5.v \
 		pll.v \
		 ../common/seven_segment.v

include ../common.mk
